package ee.mtiidla.swimresult.domain.model

class CountryCodes {

    companion object {

        fun toIso2(fina3: String) = ISO2[FINA_3.indexOf(fina3)]

        fun toFina3(iso2: String) = FINA_3[ISO2.binarySearch(iso2)]

        fun isValidFinaCountry(fina3countryCode: String) = FINA_3.contains(fina3countryCode)

        internal val ISO2 = arrayOf("AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AR", "AS", "AT", "AU", "AW", "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BM", "BN", "BO", "BR", "BS", "BT", "BW", "BY", "CA", "CD", "CF", "CG", "CH", "CI", "CK", "CL", "CM", "CN", "CO", "CR", "CU", "CV", "CW", "CY", "CZ", "DE", "DJ", "DK", "DM", "DO", "DZ", "EC", "EE", "EG", "ER", "ES", "ET", "FI", "FJ", "FM", "FO", "FR", "GB", "GD", "GE", "GH", "GI", "GM", "GN", "GQ", "GR", "GT", "GU", "GW", "GY", "HK", "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IN", "IQ", "IR", "IS", "IT", "JM", "JO", "JP", "KE", "KG", "KH", "KM", "KN", "KP", "KR", "KW", "KY", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY", "MA", "MC", "MD", "ME", "MG", "MH", "MK", "ML", "MM", "MN", "MO", "MP", "MR", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NE", "NG", "NI", "NL", "NO", "NP", "NZ", "OM", "PA", "PE", "PG", "PH", "PK", "PL", "PR", "PS", "PT", "PW", "PY", "QA", "RO", "RS", "RU", "RW", "SA", "SB", "SC", "SD", "SE", "SG", "SI", "SK", "SL", "SM", "SN", "SO", "SR", "SV", "SY", "SZ", "TC", "TD", "TG", "TH", "TJ", "TM", "TN", "TO", "TR", "TT", "TW", "TZ", "UA", "UG", "US", "UY", "UZ", "VC", "VE", "VG", "VI", "VN", "VU", "WS", "XK", "YE", "ZM", "ZW")
        internal val FINA_3 = arrayOf("AND", "UAE", "AFG", "ANT", "AGU", "ALB", "ARM", "ANG", "ARG", "ASA", "AUT", "AUS", "ARU", "AZE", "BIH", "BAR", "BAN", "BEL", "BUR", "BUL", "BRN", "BDI", "BEN", "BER", "BRU", "BOL", "BRA", "BAH", "BHU", "BOT", "BLR", "CAN", "COD", "CAF", "CGO", "SUI", "CIV", "COK", "CHI", "CMR", "CHN", "COL", "CRC", "CUB", "CPV", "CUR", "CYP", "CZE", "GER", "DJI", "DEN", "DMA", "DOM", "ALG", "ECU", "EST", "EGY", "ERI", "ESP", "ETH", "FIN", "FIJ", "FSM", "FAR", "FRA", "GBR", "GRN", "GEO", "GHA", "GIB", "GAM", "GUI", "GEQ", "GRE", "GUA", "GUM", "GBS", "GUY", "HKG", "HON", "CRO", "HAI", "HUN", "INA", "IRL", "ISR", "IND", "IRQ", "IRI", "ISL", "ITA", "JAM", "JOR", "JPN", "KEN", "KGZ", "CAM", "COM", "SKN", "PRK", "KOR", "KUW", "CAY", "KAZ", "LAO", "LBN", "LCA", "LIE", "SRI", "LBR", "LES", "LTU", "LUX", "LAT", "LBA", "MAR", "MON", "MDA", "MNE", "MAD", "MHL", "MKD", "MLI", "MYA", "MGL", "MAC", "NMA", "MTN", "MLT", "MRI", "MDV", "MAW", "MEX", "MAS", "MOZ", "NAM", "NIG", "NGR", "NCA", "NED", "NOR", "NEP", "NZL", "OMA", "PAN", "PER", "PNG", "PHI", "PAK", "POL", "PUR", "PLE", "POR", "PLW", "PAR", "QAT", "ROU", "SRB", "RUS", "RWA", "KSA", "SOL", "SEY", "SUD", "SWE", "SGP", "SLO", "SVK", "SLE", "SMR", "SEN", "SOM", "SUR", "ESA", "SYR", "SWZ", "TCN", "CHA", "TOG", "THA", "TJK", "TKM", "TUN", "TGA", "TUR", "TTO", "TPE", "TAN", "UKR", "UGA", "USA", "URU", "UZB", "VIN", "VEN", "IVB", "ISV", "VIE", "VAN", "SAM", "KOS", "YEM", "ZAM", "ZIM")
    }
}